name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.43

      - run: bun install --no-cache

      - uses: nrwl/nx-set-shas@v4

      - run: bun nx affected -t lint test build
